//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtdK22CNT3Lesson11_2210900007.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PtdCategory
    {
      
        public PtdCategory()
        {
            this.PtdProducts = new HashSet<PtdProduct>();
        }
        [Display(Name = "Ma danh muc")]
        public int PtdID { get; set; }
        [Display(Name = "Ten danh muc")]
        public string PtdCateName { get; set; }
        [Display(Name = "Trang thai")]
        public Nullable<bool> PtdStatus { get; set; }
        public virtual ICollection<PtdProduct> PtdProducts { get; set; }
    }
}
