//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtdK22CNT3Lesson11_2210900007.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtdProduct
    {
        public string Ptdid2210900007 { get; set; }
        public string PtdProName { get; set; }
        public Nullable<int> PtdCty { get; set; }
        public Nullable<double> PtdPrice { get; set; }
        public Nullable<int> PtdCateId { get; set; }
        public Nullable<int> PtdActive { get; set; }
    }
}
